name: cache validation
on: workflow_dispatch
jobs:
  cache-validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up JDK 17 and cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: cache mcn dependence
        id: cache_mvn
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: install dependencies
        if: steps.cache_mvn.outputs.cache-hit != 'true'
        run: mvn clean install
      
