name: run on success
on:
  workflow_run:
    workflows: [ "input-and-output-params" ]
    types:
      - completed

jobs:
  run-on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a test command
        run: echo "Running on success of Automation Tests workflow"