name: run on failure
on:
  workflow_run:
    workflows: [ "input-and-output-params" ]
    types:
      - completed

jobs:
  run-on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a test command
        run: echo "Running on failure of Automation Tests workflow"